#!/usr/bin/env python3
"""Client-side workflow for the integrated project.

The server accepts two kinds of connections:

1. plain HTTP, where socket bytes go directly into the HTTP parser;
2. self-written TLS, where the client first runs the custom handshake and then
   sends the same HTTP request as encrypted application data.

Run the server first:

    python3 server_side.py

Then run this client from another terminal:

    python3 client_side.py
"""

from __future__ import annotations

import argparse
import socket
from pathlib import Path

from tls_web_server.tls.certificates import load_trusted_root
from tls_web_server.tls.connection import ToyTLSClientConnection

PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_DEMO_DIR = PROJECT_ROOT / "demo_site"
HTTP_REQUEST = b"GET / HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n"


def recv_until_socket_closes(sock: socket.socket) -> bytes:
    """Read a plain HTTP response until the server closes the connection."""
    chunks = []
    while True:
        data = sock.recv(4096)
        if not data:
            break
        chunks.append(data)
    return b"".join(chunks)


def recv_tls_http_response(sock: socket.socket, tls: ToyTLSClientConnection) -> bytes:
    """Read encrypted records, decrypt them, and return the HTTP response.

    This is the client-side mirror of what the server does internally:
    TCP bytes are fed into the TLS record layer, and only decrypted plaintext is
    inspected as HTTP.
    """
    plaintext = bytearray()
    while True:
        data = sock.recv(4096)
        if not data:
            break
        tls.feed_wire_data(data)

        # The toy protocol is currently server-authenticated only, so the
        # client usually has no post-handshake bytes to send. Keeping this here
        # makes the workflow explicit and future-proof for extra client messages.
        outgoing = tls.pop_pending_wire_data()
        if outgoing:
            sock.sendall(outgoing)

        plaintext.extend(tls.read_plaintext())

        # Stop as soon as the HTTP Content-Length says the full response body
        # has arrived. This keeps the client independent of timing.
        if b"\r\n\r\n" in plaintext:
            headers, body = bytes(plaintext).split(b"\r\n\r\n", 1)
            for line in headers.split(b"\r\n"):
                if line.lower().startswith(b"content-length:"):
                    expected = int(line.split(b":", 1)[1].strip())
                    if len(body) >= expected:
                        return bytes(plaintext)
    return bytes(plaintext)


def request_plain_http(host: str, port: int) -> bytes:
    print("[client] Plain HTTP workflow")
    print("         TCP connect → send HTTP request → read HTTP response")
    with socket.create_connection((host, port), timeout=5) as sock:
        sock.sendall(HTTP_REQUEST)
        return recv_until_socket_closes(sock)


def request_http_over_self_written_tls(host: str, port: int, trusted_root_path: Path) -> bytes:
    print("[client] Self-written TLS workflow")
    print("         TCP connect")
    print("         → ClientHello with X25519 public key")
    print("         ← ServerHello + certificate chain + CertificateVerify")
    print("         → encrypted HTTP request")
    print("         ← encrypted HTTP response")

    trusted_root = load_trusted_root(trusted_root_path)
    tls = ToyTLSClientConnection(trusted_root=trusted_root, dns_name="localhost")

    with socket.create_connection((host, port), timeout=5) as sock:
        sock.sendall(tls.pop_pending_wire_data())

        while not tls.is_established:
            data = sock.recv(4096)
            if not data:
                raise RuntimeError("Server closed the connection before the TLS handshake completed")
            tls.feed_wire_data(data)
            outgoing = tls.pop_pending_wire_data()
            if outgoing:
                sock.sendall(outgoing)

        sock.sendall(tls.protect_application_data(HTTP_REQUEST))
        return recv_tls_http_response(sock, tls)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the client side of the self-written TLS + web-server demo.")
    parser.add_argument("--host", default="127.0.0.1", help="Server address. Default: 127.0.0.1")
    parser.add_argument("--plain-port", type=int, default=8080, help="Plain HTTP port. Default: 8080")
    parser.add_argument("--tls-port", type=int, default=8443, help="Self-written TLS port. Default: 8443")
    parser.add_argument("--demo-dir", type=Path, default=DEFAULT_DEMO_DIR, help="Directory generated by server_side.py.")
    args = parser.parse_args()

    root_cert = args.demo_dir / "certs" / "root_cert.pem"
    if not root_cert.exists():
        raise SystemExit("Missing demo certificate files. Start the server once with: python3 server_side.py")

    plain_response = request_plain_http(args.host, args.plain_port)
    print(plain_response.decode("utf-8", errors="replace"))

    tls_response = request_http_over_self_written_tls(args.host, args.tls_port, root_cert)
    print(tls_response.decode("utf-8", errors="replace"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
