#!/usr/bin/env python3
"""Server-side workflow for the integrated project.

This file intentionally mirrors the style of the original learning projects:

* web-server series: https://dev.to/dmytro_huz/building-your-own-web-server-part-1-theory-and-foundations-3kgo
* web-server code:   https://github.com/DmytroHuzz/build_own_webserver
* TLS series:        https://www.dmytrohuz.com/p/rebuilding-tls-from-scratch-my-complete
* TLS code:          https://github.com/DmytroHuzz/rebuilding_tls

The goal is to make the server-side workflow visible in one place:

1. prepare a tiny static website,
2. generate a local certificate chain,
3. write an NGINX-style config with one plain listener and one TLS listener,
4. start the selectors-based web server.

Run from the project root:

    python3 server_side.py

Then, in another terminal:

    python3 client_side.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

from tls_web_server.server import WebServer
from tls_web_server.tls.certificates import generate_certificate_chain

PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_DEMO_DIR = PROJECT_ROOT / "demo_site"


def prepare_demo_site(demo_dir: Path, plain_port: int, tls_port: int) -> Path:
    """Create the files needed by the standalone server demo.

    The original web-server series served files from an `html/` directory and
    read routing/listener information from an NGINX-like config file. We keep
    that same shape here so the reader can recognize the previous workflow.

    The TLS series generated a root CA, an intermediate CA, a server
    certificate, and a server private key. We reuse that workflow here because
    the TLS listener needs identity material before it can authenticate itself
    to the custom client.
    """
    html_dir = demo_dir / "html"
    certs_dir = demo_dir / "certs"
    html_dir.mkdir(parents=True, exist_ok=True)
    certs_dir.mkdir(parents=True, exist_ok=True)

    (html_dir / "index.html").write_text(
        """<!doctype html>
<html>
  <head><title>Self-written TLS + Web Server</title></head>
  <body>
    <h1>Hello from the integrated server</h1>
    <p>The HTTP response is generated by the web-server layer.</p>
    <p>When you use the TLS port, these same HTTP bytes travel inside the self-written TLS-like record layer.</p>
  </body>
</html>
""",
        encoding="utf-8",
    )

    # Regenerate on every run to keep the example self-contained. The client
    # loads the matching root certificate from this same directory.
    generate_certificate_chain(certs_dir, dns_name="localhost")

    config_path = demo_dir / "server.conf"
    config_path.write_text(
        f"""
http {{
    server {{
        listen {plain_port};
        listen {tls_port} ssl;
        server_name localhost;

        ssl_certificate certs/server_cert.pem;
        ssl_certificate_key certs/server_key.pem;
        ssl_certificate_chain certs/intermediate_cert.pem;

        location / {{
            root html;
        }}
    }}
}}
""",
        encoding="utf-8",
    )
    return config_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the server side of the self-written TLS + web-server demo.")
    parser.add_argument("--host", default="127.0.0.1", help="Address to bind. Default: 127.0.0.1")
    parser.add_argument("--plain-port", type=int, default=8080, help="Plain HTTP port. Default: 8080")
    parser.add_argument("--tls-port", type=int, default=8443, help="Self-written TLS port. Default: 8443")
    parser.add_argument("--demo-dir", type=Path, default=DEFAULT_DEMO_DIR, help="Directory for generated demo files.")
    parser.add_argument("--prepare-only", action="store_true", help="Create demo files and exit without starting the server.")
    args = parser.parse_args()

    config_path = prepare_demo_site(args.demo_dir, args.plain_port, args.tls_port)
    print(f"[server] Demo files prepared in: {args.demo_dir}")
    print(f"[server] Config written to:      {config_path}")

    if args.prepare_only:
        return 0

    server = WebServer(config_path=config_path, base_dir=args.demo_dir)
    print("[server] Starting selectors-based web server")
    print(f"[server] Plain HTTP:        http://{args.host}:{args.plain_port}/")
    print(f"[server] Self-written TLS:  {args.host}:{args.tls_port}  (use python3 client_side.py)")
    print("[server] Press Ctrl+C to stop.\n")

    try:
        server.serve_forever(host=args.host)
    except KeyboardInterrupt:
        print("\n[server] Stopping...")
        server.stop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
